package com.gliwka.hyperscan.regression;

import com.gliwka.hyperscan.wrapper.*;
import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.EnumSet;
import java.util.List;
import java.util.stream.Collectors;

import static java.util.stream.Collectors.toList;
import static org.junit.jupiter.api.Assertions.*;

// https://github.com/gliwka/hyperscan-java/issues/228
// Upstream: https://github.com/VectorCamp/vectorscan/issues/317
public class Gh228VectorscanX86RegressionTest {
    @Test
    void shouldHaveAMatch() throws CompileErrorException {
        Scanner scanner = new Scanner();

        EnumSet<ExpressionFlag> flags = EnumSet.of(
                ExpressionFlag.SINGLEMATCH,
                ExpressionFlag.ALLOWEMPTY,
                ExpressionFlag.UTF8,
                ExpressionFlag.PREFILTER
        );

        List<String> regex = Arrays.asList(new String[] {
                "^muvoy-nyemcynjywynamlahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^muvoy-nylyflahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^muvoy-wyljafo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^muvoy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^muvoazy-ailyjmflahio/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mffhvil-uvoaiyoo-mnwai/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mffhvil-ailysjalc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mffhvil-oyfvjalc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mffhvil-lcqyo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mfeoyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mny-nmlm-qjhnvflo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mny-ytlyjimeo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mny-jyz-sfq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnjyzayk-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-mqa-mimeclafo-khjdyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-mqa/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-mlljauvlahi-xy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-mlljauvlahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-mvlghjabmlahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-ua-nmlmljmioryj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-uaeeais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-ujmin-wymovjywyil/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-ujmin-ovjzyco/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-uo-jyzayk-lhhe/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-fmwqmasi-mimeclafo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-fhjy-ehso/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-nmlm-yis/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-njvan/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-wmq-uannyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-wmjdylqemfy-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-ihlarafmlahio/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-qmfais-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-qmfais-lyolais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-qyjrhjwmify/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-qatye/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-qhkyjlhheo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-qjynaflahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-jmidais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-jyqhoalhjc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-jyzofa-remllyiyn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-ofjauy-yzyil-ux-ocif/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-lqw/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-ljyinonmog/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-lkyyl-fhwqhoyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-va-yzyilo-remllyiyn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-voyjwhnyeais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno-zanyh-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno_fhjy_remllyiyn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mno_wmjdylqemfy_qjyolh/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnono-yijafgyn-voyj-awq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnoqjazmfc-xy-mffyoo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnoqjazmfc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnojll/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnolkyyloyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnljmfdyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnljmfdyjolmsais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mnzyjlaoyj-mqa/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^myw/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^myw_rhilo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mrraeamly-yirhjfyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^msmemlmi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^msmlgm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^msyil-lhheo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^manyi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^majrehk-hdlm-voyjo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mdmogq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^meumlho/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^meyjluhmjn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mwea-sfq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mwqearc-qjhn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mwqearc-qjhsjmw-wmimsyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mwqearc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mimeclafo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mila-oqmw/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mqmfgy-olmlaf-oalyo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mqq-qjhtc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mvnayify-jykmjno/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mvnayifyo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mvnal-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mvjhjm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mvlg-wylmnmlm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^mvlhwmlyn-rymlvjy-qaehl/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^umnoymjfguhl/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^umlfg-mflahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^umbye-lhheo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uasxvyjc-fgmjsyumfd/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uasxvyjc-nmjloyfvjalc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uasxvyjc-yjmoyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uasxvyjc-ehmnyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uasxvyjc-jysaoljmlahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uasxvyjc-vomsy-zaykyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uaslmueyjys/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uaeeais-qemlrhjw/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uaeeaisoyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uaeeaisoyjzafyolmsais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uajnkmlfg-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ualo-xy-mffyoo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uabaioasglo-rhjyfmol-j/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uabaioasglo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uabqjhraeyo-oyjzafymffl/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uehuolhjy-majrehk/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uehuolhjy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uhlwmdyj-reml-ehs/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uhlwmdyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uhvifyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ux-lgjarl-aneo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ux-zyjlafm-gymelg-qm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ujmin-omrylc-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ujmin-ovjzyco-kyu/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ujminyn-fw/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uvaenfmfgy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uvoaiyoo-fyilyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uvoaiyoo-aiuht/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^uvoaiyoo-oyllaiso/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lawyeaiywatyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lawyeaiyjmidyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lawyeaiyofhjyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lawyeaiyoyjzafy-mqa/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lawyeaiyoyjzafy-olmsais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lawyeaiyoyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^laq_oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lhqujman/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lhqaf-ohfame-qjhhr/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lhqafot-jfq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lhj-whi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^ljmiowhsjarayj-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lonu/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^loo-sfq-fyjl-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkyyl-yilalc-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkyylnyfd/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkyylcqay-olmsais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkaqqc-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkalfgyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkallyj-ihlyuhhd/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lkllj-majrehk-qds/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lcqymgymn-watyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lcqymgymn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^lcjahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^vnew/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^vnq-nyz/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^vqehmn-wynam-oyjzyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^voyj-yilalc-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^voyj-awmsy-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^voyj-waeyolhiyo-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^voyj-oasime-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^voyj-lkyyl-sjmqg/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zanyh-fhhjnaimlhj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zanyh-watyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zanyh-ihjwmeabmlahi-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zanyh-ovwwmjc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zanyh-ljmiofhnyj-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zanyhuajn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zaheyify-min-shjy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zjq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^zveinu/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^kminu/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^kyu-qmcwyilo-gllq/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^kyu-qmcwyilo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^kyumr-fa/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^tt-iork/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^bgyiswaiso/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fmimjc-mimecoao/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fmq-yis/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fmoohkmjc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fne-nyz-uevyuajn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fne-nyz-ay/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fne-nyz-we/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fne-nyz-jyzyivy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fyohvjfy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fgmjsyumfd/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fgvuucoiaqy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fa-airjm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^faw-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^faoo-lhheuht/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fazaf-ailysjalc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^feafdghvoy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^feayil-nmlm-yisaiyyjais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^feayilyzyil-wynam-raelyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fehvn-nmlmljmioryj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fehvnogvlley/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fehvnoxejys/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fevolyj-jysaoljc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fio-olmsais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhwwyjfy-nmlm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhwwvialayo-no/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhwwvialayo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhwqeamify/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhwqhoyj-uylm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhwqvly/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhiras-nmlm-jysaoljmlahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhiras-yisaiy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhirasuvo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhilyil-xvmealc/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhiljhelhkyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhizyjoahi-yzyil-wmimsyj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhizyjoahimlljauvlahi/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhhjn-mvnalhj/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhhjn-wmailyimify/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",

                "^cop/devel/workflows-(prod|test)-.*/[0-9]+$", // Regex pattern that will match our fixture

                "^fhjy-mqa-lhheo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhjy-nmlm-eaujmjayo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhjywyljafo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhjlyt-majrehk/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhjlyt-wylm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fhjlyt/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fjymlazyo-nmlmoylo/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fjymlhjo-nmlm/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fjynyilame-oyjzafy/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^foq-jyqhjlais/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fvmn/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fvjmlahi-va/nyzye/khjdrehko-(qjhn|lyol)-.*/0$",
                "^fvolhwyj-ytqyjayify-mqqo/nyzye/khjdrehko-.*/0$"
        });

        List<Expression> expressions = regex.stream().map(expr -> new Expression(expr, flags)).collect(toList());

        Database db = Database.compile(expressions);

        scanner.allocScratch(db);
        List<Match> matches = scanner.scan(db, "cop/devel/workflows-prod-build-cop-cop-ingestor/0");
        assertFalse(matches.isEmpty());
    }
}
